# Generated by Django 5.2.3 on 2025-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramaccount',
            name='users_teleg_telegra_9eafce_idx',
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['telegram_id', 'user', 'is_active'], name='users_teleg_telegra_e230c0_idx'),
        ),
    ]
