# Generated by Django 5.2.3 on 2025-08-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftusage',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.gift'),
        ),
        migrations.AddField(
            model_name='giftusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderbuy',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balance.buy'),
        ),
        migrations.AddField(
            model_name='orderbuy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='giftusage',
            index=models.Index(fields=['user', 'gift'], name='balance_gif_user_id_35fb59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='giftusage',
            unique_together={('user', 'gift')},
        ),
    ]
