# Generated by Django 5.2.3 on 2025-08-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='order.order'),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='telegram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramaccount'),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_active'], name='order_order_status_03925c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active', 'created_at'], name='order_order_is_acti_26a2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['order', 'user', 'telegram'], name='order_order_order_i_8ff62d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['user', 'telegram', 'joined_at'], name='order_order_user_id_7b3db9_idx'),
        ),
    ]
