# Generated by Django 5.2.3 on 2025-09-26 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        ('service', '0002_alter_service_price'),
        ('users', '0003_remove_telegramaccount_users_teleg_telegra_e230c0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_status_03925c_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_is_acti_26a2cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordermember',
            name='order_order_user_id_7b3db9_idx',
        ),
        migrations.AddField(
            model_name='ordermember',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active', 'status'], name='order_order_is_acti_eaf317_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['joined_at'], name='order_order_joined__5382a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['is_active'], name='order_order_is_acti_a5890c_idx'),
        ),
    ]
