# Generated by Django 5.2.3 on 2025-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_order_order_status_03925c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermember',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='ordermember',
            name='paid',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PENDING', max_length=20),
        ),
    ]
