# Generated by Django 5.2.3 on 2025-10-07 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_ordermember_is_paid_ordermember_paid'),
        ('users', '0003_remove_telegramaccount_users_teleg_telegra_e230c0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermember',
            name='pair_key',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['pair_key'], name='order_order_pair_ke_725446_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordermember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order', 'telegram', 'user'), name='unique_active_order_member'),
        ),
    ]
