# Generated by Django 5.2.3 on 2025-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermember_pair_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
